package com.assigment.decisionruletemplate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String rere;

	private java.lang.Float ffe;

	public Product() {
	}

	public java.lang.String getRere() {
		return this.rere;
	}

	public void setRere(java.lang.String rere) {
		this.rere = rere;
	}

	public java.lang.Float getFfe() {
		return this.ffe;
	}

	public void setFfe(java.lang.Float ffe) {
		this.ffe = ffe;
	}

	public Product(java.lang.String rere, java.lang.Float ffe) {
		this.rere = rere;
		this.ffe = ffe;
	}

}