package com.assigment.decisionruletemplate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String productDetail;

	public test() {
	}

	public java.lang.String getProductDetail() {
		return this.productDetail;
	}

	public void setProductDetail(java.lang.String productDetail) {
		this.productDetail = productDetail;
	}

	public test(java.lang.String productDetail) {
		this.productDetail = productDetail;
	}

}